/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package manage_rooms;

/**
 *
 * @author Acer
 */

import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;
//import java.util.Scanner;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableModel ;
import javax.swing.RowFilter;

public class RoomPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomPanel
     */
    
          Scanner input= new Scanner(System.in);
    private JPopupMenu option = new  JPopupMenu();
      private JMenuItem edit = new JMenuItem("edit");
       private JMenuItem delete = new JMenuItem("delete");
       
       
    public RoomPanel() {
        initComponents();
        
        
        
          loadTableData();
        //    tableInfo.setAutoCreateRowSorter(true);
       TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tableInfo.getModel());
tableInfo.setRowSorter(sorter);
       //   option.add("edit");
     //      option.add("delete");
          option.add(edit);
           option.add(delete);
           
           
           
          delete.addActionListener(e -> {
    int rowline = tableInfo.getSelectedRow();
    if (rowline != -1) {

        DefaultTableModel model = (DefaultTableModel) tableInfo.getModel();

        // Example: delete based on Room Number (first column)
        String value = model.getValueAt(rowline, 0).toString();

        // Remove from JTable
        model.removeRow(rowline);

        // Remove from file
        deleteRecordFromFile(value);

        JOptionPane.showMessageDialog(null, "Record deleted successfully.");
    }} );
        
  
           tableInfo.getModel().addTableModelListener(e -> {
        if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
        int row = e.getFirstRow();
        int column = e.getColumn();
        
        if (column == 0) {//roomnum cannot be modified because the systemn need to avoid duplication of room number
            JOptionPane.showMessageDialog(RoomPanel.this, 
                "Room Number cannot be modified!");
            loadTableData(); // Reload original data
            return;
        }
    
          if (column == 5) {//roomnum cannot be modified because the systemn need to avoid duplication of room number
            JOptionPane.showMessageDialog(RoomPanel.this, 
                "Room Number cannot be modified!");
            loadTableData(); // Reload original data
            return;
        }
    

        DefaultTableModel model = (DefaultTableModel) tableInfo.getModel();
        String updatedValue = model.getValueAt(row, column).toString();
        String roomNumber = model.getValueAt(row, 0).toString(); // Use Room Number as ID

        // Update the file
       boolean filled= updateRecordInFile(roomNumber, row, column, updatedValue);//if all info is fill when u
       
       

        // Show success message
        if(filled){
        JOptionPane.showMessageDialog(RoomPanel.this, "Record updated successfully!");
    }}
});
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        addroombtn = new javax.swing.JButton();

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room Number", "Room Type", "Bed Type", "Max. ", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableInfo);

        addroombtn.setText("+ADD ROOM");
        addroombtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroombtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addroombtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addroombtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:

        String input = search.getText().trim();

    }//GEN-LAST:event_searchActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        //    private void searchKeyReleased(java.awt.event.KeyEvent evt) {
            // TODO add your handling code here:
            String searchText = search.getText().trim(); // Fixed variable name

            // Get the current model from tableInfo (not showTable)
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tableInfo.getModel());
            tableInfo.setRowSorter(sorter);

            if (!searchText.isEmpty()) {
                // Search in ALL columns (0-5)
                sorter.setRowFilter(RowFilter.regexFilter("(?i)"+ searchText));
                // (?i) makes it case-insensitive

                if(tableInfo.getRowCount()==0){
                    JOptionPane.showMessageDialog(null,"No Record is Found");

                }

            }

    }//GEN-LAST:event_searchKeyReleased
    
        public int linearSearch(String keyword) {
    DefaultTableModel model = (DefaultTableModel) tableInfo.getModel();

    for (int row = 0; row < model.getRowCount(); row++) {
        for (int col = 0; col < model.getColumnCount(); col++) {

            Object value = model.getValueAt(row, col);
            if (value != null && value.toString().toLowerCase()
                    .contains(keyword.toLowerCase())) {

                return row; // FOUND → return row index
            }
        }
    }
    return -1; // NOT FOUND
}

     
    private void tableInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableInfoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2){
            int row = tableInfo.rowAtPoint(evt.getPoint());
            tableInfo.setRowSelectionInterval(row,row);
            option.show(tableInfo,evt.getX(),evt.getY());
        }
    }//GEN-LAST:event_tableInfoMouseClicked

    private void addroombtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroombtnActionPerformed
        // TODO add your handling code here:                                        
    // 1. Create a generic Window (JFrame) to hold your panel
    javax.swing.JFrame window = new javax.swing.JFrame("Add New Room");
    
    // 2. Create your "Add Room" Panel
    manage_rooms.RoomPanel2 panel = new manage_rooms.RoomPanel2(this);
    
    // 3. Put the Panel inside the Window
    window.add(panel);
    window.pack(); // Size the window to fit the panel
    window.setLocationRelativeTo(null); // Center the window
    window.setVisible(true); // Show it!
        
        

    }//GEN-LAST:event_addroombtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addroombtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables

    void loadTableData() {
         DefaultTableModel modelr = (DefaultTableModel) tableInfo.getModel();// In defaultTableModel it allows to add,update,delete
        modelr.setRowCount(0); // clear existing rows, pag wala neto itshows  the empty rows
     //   try( Scanner br  = new  ScannerReader(new FileReader(manageroom.txt))  ){
       try (BufferedReader br = new BufferedReader(new FileReader("data/rooms.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(","); 
                modelr.addRow(data);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error loading table: " + e.getMessage());
        
    }
         tableInfo.setAutoCreateRowSorter(true);
    }

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from
    }

    
    private void deleteRecordFromFile(String searchvalue) {
            File inputFile = new File("data/rooms.txt");
    File tempFile = new File("temp.txt");

    try (
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        PrintWriter writer = new PrintWriter(new FileWriter(tempFile))
    ) {
        String line;
        boolean found = false;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",");
            Object searchValue = null;
            // Example: data[0] = Room Number
            // Change this based on your file structure
            if (data[0].equals(searchValue)) {
                found = true;
                continue;   // Skip writing (delete)
            }
            writer.println(line); // keep other lines
        }
       

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error deleting record: " + e.getMessage());
    }
    // Replace original file
    inputFile.delete();
    tempFile.renameTo(inputFile);
    }

    private boolean updateRecordInFile(String roomNumber, int row, int column, String updatedValue) {
            File inputFile = new File("data/rooms.txt");
    File tempFile = new File("temp.txt");
    
    if (updatedValue == null || updatedValue.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fill in all information.");
      //   loadTableData(); // reload original data
       return false;
    
    }
           
    try (BufferedReader reader = new BufferedReader(new FileReader(inputFile));
         PrintWriter writer = new PrintWriter(new FileWriter(tempFile))) {
        
        

        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(","); // assumes space-separated columns
            if (data.length > 0 && data[0].equalsIgnoreCase(roomNumber)) {
                 
                data[column] = updatedValue; // update the specific column
                line = String.join(" ", data);
            }
            writer.println(line);
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error updating record: " + ex.getMessage());
       return false;
    }

    inputFile.delete();
    tempFile.renameTo(inputFile);
    return true;
    }
}


   
