/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package reports;

/**
 *
 * @author Acer
 */

import java.io.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form BillingData
     */
    public ReportPanel() {
        initComponents();
        loadRevenueData();//loads all report agad agad
    }
    
    private void loadRevenueData() {
    ReportData dataLogic = new ReportData();//instance
    
    // pass yung label sa Report Data
    dataLogic.updateRevenueLabels(lblDailySales, lblMonthlySales, lblWeeklySales, lblTotalCheckouts);
    updateCheckInCount();//count ilang customer nagcheckin tapos display sa lblTotalCheckIn

    
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();//access table
    model.setRowCount(0); //clear yung previous records

    ArrayList<String[]> allBills = dataLogic.getAllBills();//retrieve yung laman ng bills.txt
    for (String[] b : allBills) {
        if (b.length >= 16) {
            Object[] row = {
                b[2],                   // customer name
                b[5],                   // room no.
                b[9] + " to " + b[10],  // check in check out
                "₱" + b[15]             // grand total
            };
            model.addRow(row);
        }
    }
}
    
    private void updateCheckInCount() {//cpunt yung total checkins from record.txt
        int count = 0;
        try (BufferedReader br = new BufferedReader(new FileReader("data/records.txt"))) {
            while (br.readLine() != null) { count++; }//everyline isang checkin tapos count ng total
        } catch (IOException e) { }
        lblTotalCheckIn.setText(String.valueOf(count));//display
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTotalCheckIn = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblcheck = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotalCheckouts = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblDaily = new javax.swing.JLabel();
        lblDailySales = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblMonthlySales = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3Weekly = new javax.swing.JPanel();
        lblWeeklyHeader = new javax.swing.JLabel();
        lblWeeklySales = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(75, 146, 219));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 1000, -1));

        lblTotalCheckIn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalCheckIn.setText("0");

        jLabel11.setText("(Today/Month):");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Total Check-ins");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(lblTotalCheckIn))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotalCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 100));

        lblcheck.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblcheck.setText("Total Check-outs");

        jLabel10.setText("(Today/Month):");

        lblTotalCheckouts.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTotalCheckouts.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalCheckouts)
                    .addComponent(jLabel10)
                    .addComponent(lblcheck, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalCheckouts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 180, 100));

        lblDaily.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDaily.setText("Total Sales (Daily):");

        lblDailySales.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblDailySales.setText("₱0.00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDailySales)
                    .addComponent(lblDaily))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDaily)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDailySales)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 180, 100));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Total Sales (Monthly):");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 136, -1));

        lblMonthlySales.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblMonthlySales.setText("₱0.00");
        jPanel7.add(lblMonthlySales, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 170, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REVENUE / SALES REPORT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("REVENUE / SALES REPORT MODULE(ADMIN ONLY)");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer", "Room No.", "Check_In/Out Dates", "Amount Paid"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(666, 666, 666))
            .addComponent(jScrollPane1)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 960, -1));

        lblWeeklyHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWeeklyHeader.setText("Total Sales(Weekly):");

        lblWeeklySales.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWeeklySales.setText("₱0.00");

        javax.swing.GroupLayout jPanel3WeeklyLayout = new javax.swing.GroupLayout(jPanel3Weekly);
        jPanel3Weekly.setLayout(jPanel3WeeklyLayout);
        jPanel3WeeklyLayout.setHorizontalGroup(
            jPanel3WeeklyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3WeeklyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3WeeklyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWeeklyHeader)
                    .addComponent(lblWeeklySales))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel3WeeklyLayout.setVerticalGroup(
            jPanel3WeeklyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3WeeklyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWeeklyHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWeeklySales)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3Weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 170, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        loadRevenueData();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3Weekly;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDaily;
    private javax.swing.JLabel lblDailySales;
    private javax.swing.JLabel lblMonthlySales;
    private javax.swing.JLabel lblTotalCheckIn;
    private javax.swing.JLabel lblTotalCheckouts;
    private javax.swing.JLabel lblWeeklyHeader;
    private javax.swing.JLabel lblWeeklySales;
    private javax.swing.JLabel lblcheck;
    // End of variables declaration//GEN-END:variables
}
