/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package check_out;

/**
 *
 * @author Acer
 */
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;

public class CheckOutPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckOutPanel
     */
    
    CheckOutData checkout = new CheckOutData();
    
    private double hiddenExtraFee = 0.0;
    
    public CheckOutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CheckOutPanel = new javax.swing.JPanel();
        SearchPanel = new javax.swing.JPanel();
        SearchRoomNum = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        customerRoomPanel = new javax.swing.JPanel();
        CheckOutSection = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRoomType = new javax.swing.JTextField();
        txtCheckInDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkOutDate = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDays = new javax.swing.JTextField();
        txtBedType = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtRoomNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FindBillConfiPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtotalAmount = new javax.swing.JLabel();
        btnConfirmCheckOut = new javax.swing.JButton();
        addRequest = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lessDisc = new javax.swing.JTextField();
        totalStay = new javax.swing.JTextField();
        roomCharges = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        addPersonFees = new javax.swing.JTextField();

        CheckOutPanel.setBackground(new java.awt.Color(153, 204, 255));
        CheckOutPanel.setMaximumSize(new java.awt.Dimension(1200, 700));
        CheckOutPanel.setPreferredSize(new java.awt.Dimension(1200, 700));
        CheckOutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchPanel.setBackground(new java.awt.Color(153, 204, 255));

        SearchRoomNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SearchRoomNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchRoomNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchRoomNumActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(24, 24, 24))
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchRoomNum, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                .addContainerGap())
        );

        CheckOutPanel.add(SearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1054, 6, 428, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("CUSTOMER CHECK OUT SECTION");
        CheckOutPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        customerRoomPanel.setBackground(new java.awt.Color(75, 146, 219));
        customerRoomPanel.setForeground(new java.awt.Color(204, 204, 204));

        CheckOutSection.setBackground(new java.awt.Color(0, 102, 204));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CUSTOMER + ROOM INFO");

        javax.swing.GroupLayout CheckOutSectionLayout = new javax.swing.GroupLayout(CheckOutSection);
        CheckOutSection.setLayout(CheckOutSectionLayout);
        CheckOutSectionLayout.setHorizontalGroup(
            CheckOutSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CheckOutSectionLayout.setVerticalGroup(
            CheckOutSectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckOutSectionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtMobile.setEditable(false);
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtRoomType.setEditable(false);
        txtRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomTypeActionPerformed(evt);
            }
        });

        txtCheckInDate.setEditable(false);
        txtCheckInDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCheckInDateActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        jLabel5.setText("Room Type:");

        jLabel6.setText("Email:");

        jLabel7.setText("Mobile Number:");

        jLabel9.setText("Check- in Date:");

        jLabel10.setText(" Check - out Date:");

        checkOutDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutDateActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel17.setText("Bed Type:");

        txtPrice.setEditable(false);
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        jLabel12.setText("Number of days stayed: ");

        txtDays.setEditable(false);
        txtDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDaysActionPerformed(evt);
            }
        });

        txtBedType.setEditable(false);
        txtBedType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBedTypeActionPerformed(evt);
            }
        });

        jLabel18.setText("Price:");

        txtRoomNum.setEditable(false);
        txtRoomNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNumActionPerformed(evt);
            }
        });

        jLabel8.setText("Room Number: ");

        javax.swing.GroupLayout customerRoomPanelLayout = new javax.swing.GroupLayout(customerRoomPanel);
        customerRoomPanel.setLayout(customerRoomPanelLayout);
        customerRoomPanelLayout.setHorizontalGroup(
            customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckOutSection, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(customerRoomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerRoomPanelLayout.createSequentialGroup()
                        .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerRoomPanelLayout.createSequentialGroup()
                                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerRoomPanelLayout.createSequentialGroup()
                                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRoomNum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMobile, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, customerRoomPanelLayout.createSequentialGroup()
                                        .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(12, 12, 12)))
                        .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5)
                                .addComponent(jLabel17)
                                .addComponent(txtBedType, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                .addComponent(txtRoomType))
                            .addGroup(customerRoomPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel12)))
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDays, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(customerRoomPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerRoomPanelLayout.createSequentialGroup()
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(customerRoomPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerRoomPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
        );
        customerRoomPanelLayout.setVerticalGroup(
            customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerRoomPanelLayout.createSequentialGroup()
                .addComponent(CheckOutSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBedType, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDays, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRoomNum, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(customerRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCheckInDate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CheckOutPanel.add(customerRoomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));

        FindBillConfiPanel.setBackground(new java.awt.Color(75, 146, 219));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FINAL BILLING & CONFIRMATION ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel14.setText("Total Stay Duration:");

        jLabel11.setText("Room Charges (Price x Duration):");

        jLabel16.setText("Additional Request:");

        jPanel7.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel21.setText("Less Discount:");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("TOTAL AMOUNT DUE: ");

        txtotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(txtotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnConfirmCheckOut.setBackground(new java.awt.Color(0, 102, 204));
        btnConfirmCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmCheckOut.setText("CONFIRM CHECK-OUT");
        btnConfirmCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmCheckOutActionPerformed(evt);
            }
        });

        addRequest.setEditable(false);
        addRequest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRequestActionPerformed(evt);
            }
        });
        addRequest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addRequestKeyReleased(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(0, 102, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        lessDisc.setEditable(false);
        lessDisc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lessDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lessDiscKeyReleased(evt);
            }
        });

        totalStay.setEditable(false);
        totalStay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        roomCharges.setEditable(false);
        roomCharges.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel15.setText("Additional Person Fees:");

        addPersonFees.setEditable(false);
        addPersonFees.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addPersonFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonFeesActionPerformed(evt);
            }
        });
        addPersonFees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addPersonFeesKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout FindBillConfiPanelLayout = new javax.swing.GroupLayout(FindBillConfiPanel);
        FindBillConfiPanel.setLayout(FindBillConfiPanelLayout);
        FindBillConfiPanelLayout.setHorizontalGroup(
            FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindBillConfiPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel21))
                .addGap(50, 50, 50)
                .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lessDisc, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(addRequest)
                    .addComponent(totalStay)
                    .addComponent(roomCharges)
                    .addComponent(addPersonFees))
                .addGap(17, 17, 17))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindBillConfiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FindBillConfiPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnConfirmCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        FindBillConfiPanelLayout.setVerticalGroup(
            FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FindBillConfiPanelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(totalStay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FindBillConfiPanelLayout.createSequentialGroup()
                        .addComponent(roomCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FindBillConfiPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(92, 92, 92))
                    .addGroup(FindBillConfiPanelLayout.createSequentialGroup()
                        .addComponent(addPersonFees, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(FindBillConfiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lessDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(35, 35, 35)))
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnConfirmCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        CheckOutPanel.add(FindBillConfiPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CheckOutPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CheckOutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchRoomNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchRoomNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchRoomNumActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String roomNumber = SearchRoomNum.getText().trim();

        // ... (Existing validations for empty string and isRoomValid) ...

        CheckOutData.Customer customer = checkout.searchCustomerByRoom(roomNumber);

        if (customer != null) {
            // 1. Fill Text Info
            txtName.setText(customer.name.replace("_", " "));
            
            txtMobile.setText(customer.mobile);
            txtEmail.setText(customer.email);
            txtRoomType.setText(customer.roomType);
            txtBedType.setText(customer.bedType);
            
            txtRoomNum.setText(customer.roomNumber);
            txtPrice.setText(String.valueOf(customer.price));
            txtCheckInDate.setText(customer.checkIn);

            //  Load ALL Fees from File
            addPersonFees.setText(String.valueOf(customer.extraPersonFee));
            addRequest.setText(String.valueOf(customer.extraRequestFee));
           
            
            lessDisc.setText(String.valueOf(customer.discount)); // Loaded from File

            // Calculate Stay Duration
            LocalDate today = LocalDate.now();
            checkOutDate.setText(today.toString());
            long days = 1;
            try {
                days = ChronoUnit.DAYS.between(LocalDate.parse(customer.checkIn), today);
                if (days <= 0) days = 1;
            } catch(Exception e) { days = 1; }

            txtDays.setText(String.valueOf(days));
            totalStay.setText(String.valueOf(days));

            // Calculate Final Total
            double roomTotal = customer.price * days;
            roomCharges.setText("" + roomTotal);

            // Formula: (Room Charge + Extras) - Discount
            double finalTotal = (roomTotal + customer.extraPersonFee + customer.extraRequestFee) - customer.discount;
            txtotalAmount.setText("" + finalTotal);
            
            hiddenExtraFee = customer.extraRequestFee;

        } else {
            JOptionPane.showMessageDialog(this, "No active guest in room " + roomNumber);
            clearFields();
        }
        calculateTotal();

    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void clearFields() {
    txtName.setText("");
    txtMobile.setText("");
    txtEmail.setText("");
    txtRoomNum.setText("");
    txtRoomType.setText("");
    txtBedType.setText("");
    txtPrice.setText("");
    txtCheckInDate.setText("");
    checkOutDate.setText("");
    txtDays.setText("");
    addPersonFees.setText("");
    addRequest.setText("");
    lessDisc.setText("");
    roomCharges.setText("");
    totalStay.setText("");
    txtotalAmount.setText("");
    SearchRoomNum.setText("");
}

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
        txtName.setEditable(false);
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomTypeActionPerformed

    private void txtCheckInDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCheckInDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCheckInDateActionPerformed

    private void checkOutDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutDateActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDaysActionPerformed

    private void txtBedTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBedTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBedTypeActionPerformed

    private void txtRoomNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNumActionPerformed
        // TODO add your handling code here:
        txtRoomNum.setEditable(false);
    }//GEN-LAST:event_txtRoomNumActionPerformed

    private void btnConfirmCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmCheckOutActionPerformed
    String roomNumber = txtRoomNum.getText().trim();
        
        // 1. Validation: Check if a room is selected
        if (roomNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search for a room first.");
            return;
        }
        
        // 2. Validation: Check if total is valid
        if (txtotalAmount.getText().equals("0.00") || txtotalAmount.getText().isEmpty()) {
             JOptionPane.showMessageDialog(this, "Total amount is invalid. Please check details.");
             return;
        }

        try {
            // 3. Gather Final Numbers from the Text Fields (and hidden variable)
            double extraPerson = Double.parseDouble(addPersonFees.getText().isEmpty() ? "0" : addPersonFees.getText());
            
            // Use the hidden variable for Extra Request (Safe)
            double extraRequest = hiddenExtraFee; 
            
            double discount = Double.parseDouble(lessDisc.getText().isEmpty() ? "0" : lessDisc.getText());
            double total = Double.parseDouble(txtotalAmount.getText());

            // 4. Call the Data Class to Process Checkout
            // This saves to bills.txt, records.txt and updates customers.txt
            boolean success = checkout.checkoutCustomer(roomNumber, extraPerson, extraRequest, discount, total);

            // 5. Feedback
            if (success) {
                JOptionPane.showMessageDialog(this, "Checkout Successful!\nGuest Checked Out & Bill Saved.");
                clearFields(); // Clear the screen
            } else {
                JOptionPane.showMessageDialog(this, "Checkout Failed. Please try again.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error processing checkout: " + e.getMessage());
        }
    }//GEN-LAST:event_btnConfirmCheckOutActionPerformed

    private void addRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRequestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addRequestActionPerformed

    private void addRequestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addRequestKeyReleased
        // TODO add your handling code here:
        calculateTotal();
    }//GEN-LAST:event_addRequestKeyReleased

    private void lessDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lessDiscKeyReleased
        // TODO add your handling code here:
        calculateTotal();
    }//GEN-LAST:event_lessDiscKeyReleased
    //method for calculation
    private void calculateTotal() {
    try {
        double baseRoomCharge = Double.parseDouble(roomCharges.getText().isEmpty() ? "0" : roomCharges.getText());
        double extraPerson = Double.parseDouble(addPersonFees.getText().isEmpty() ? "0" : addPersonFees.getText());
        
        
        double extraReq = hiddenExtraFee;
        double discount = Double.parseDouble(lessDisc.getText().isEmpty() ? "0" : lessDisc.getText());
        
        

        double finalTotal = (baseRoomCharge + extraPerson + extraReq) - discount;
        
        txtotalAmount.setText("" + finalTotal);

        if (finalTotal < 0) finalTotal = 0;
        
        txtotalAmount.setText("" + finalTotal);
        
    } catch (NumberFormatException e) {
        txtotalAmount.setText("0.00");
    }
}

    private void addPersonFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPersonFeesActionPerformed

    private void addPersonFeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addPersonFeesKeyReleased
        // TODO add your handling code here:
        calculateTotal();
    }//GEN-LAST:event_addPersonFeesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CheckOutPanel;
    private javax.swing.JPanel CheckOutSection;
    private javax.swing.JPanel FindBillConfiPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JTextField SearchRoomNum;
    private javax.swing.JTextField addPersonFees;
    private javax.swing.JTextField addRequest;
    private javax.swing.JButton btnConfirmCheckOut;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField checkOutDate;
    private javax.swing.JPanel customerRoomPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField lessDisc;
    private javax.swing.JTextField roomCharges;
    private javax.swing.JTextField totalStay;
    private javax.swing.JTextField txtBedType;
    private javax.swing.JTextField txtCheckInDate;
    private javax.swing.JTextField txtDays;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtRoomNum;
    private javax.swing.JTextField txtRoomType;
    private javax.swing.JLabel txtotalAmount;
    // End of variables declaration//GEN-END:variables
}
